apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - image: mysql:5.5
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef: mysql
            key: password
            name: mysql
    name: mysql